apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: react-de-deployment
spec:
  selector:
    matchLabels:
      app: react
  replicas: 1 # number of pods
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: reactdockercd3
          image: us.gcr.io/reactdockerde2/desite/reactdockercd3:a126561887b3f372154384df030948cb5cc67fee
          ports:
            - containerPort: 443
