# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
kind: Service
apiVersion: v1
metadata:
  name: react-de-service
spec:
  selector:
    app: react
  ports:
    - protocol: TCP
      port: 80 # abstracted Service port, which can be any port other pods use to access the Service
      targetPort: 443 # port the container accepts traffic on
  type: LoadBalancer
